export default [
  {
    // https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov
    // https://drive.google.com/file/d/1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov/view?usp=sharing
    topicName: "Computer Science Eng.",
    position: 0,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        S_Code: "CS-424",
        Topic: "computerscience",
        Problem: "Distributed Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-423",
        Topic: "computerscience",
        Problem: "Information Security Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-422",
        Topic: "computerscience",
        Problem: "Web Technology Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-421",
        Topic: "computerscience",
        Problem: "Multimedia Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-411",
        Topic: "computerscience",
        Problem: "Mobile Computing Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-412",
        Topic: "computerscience",
        Problem: "Advanced Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-413",
        Topic: "computerscience",
        Problem: "Distributed Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-414",
        Topic: "computerscience",
        Problem: "Neural Networks Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-415",
        Topic: "computerscience",
        Problem: "Computer Graphic Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-416",
        Topic: "computerscience",
        Problem: "Mobile APplication Development Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-321",
        Topic: "computerscience",
        Problem: "Principles of Compiler Design Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-322",
        Topic: "computerscience",
        Problem: "Microprocessor Interfacing and MC Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-323",
        Topic: "computerscience",
        Problem: "Design & Analysis of Algorithms Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-324",
        Topic: "computerscience",
        Problem: "Computer Networks Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-325",
        Topic: "computerscience",
        Problem: "Operating Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-326",
        Topic: "computerscience",
        Problem: "Software Engineering Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-311",
        Topic: "computerscience",
        Problem: "Thoery of Computation Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-312",
        Topic: "computerscience",
        Problem: "Java Pragramming Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-313",
        Topic: "computerscience",
        Problem: "Data Communication and Networks Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-314",
        Topic: "computerscience",
        Problem: "Computer Architecture Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-315",
        Topic: "computerscience",
        Problem: "Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-316",
        Topic: "computerscience",
        Problem: "Pulse, Digital & Wave Shaping Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-222",
        Topic: "computerscience",
        Problem: "Discrete Mathematical Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-221",
        Topic: "computerscience",
        Problem: "Computer Organization Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-222",
        Topic: "computerscience",
        Problem: "Data Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-228",
        Topic: "computerscience",
        Problem: "Communication Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-224",
        Topic: "computerscience",
        Problem: "Microprocessors 8085 & 8086 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-225",
        Topic: "computerscience",
        Problem: "System Software Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-211",
        Topic: "computerscience",
        Problem: "Mathematics 3 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-211",
        Topic: "computerscience",
        Problem: "Digital Logic Design Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-212",
        Topic: "computerscience",
        Problem: "Unix and shell programming Lab Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-213",
        Topic: "computerscience",
        Problem: "Object Oriented Programming with C++ Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-214",
        Topic: "computerscience",
        Problem: "Principles of Programming Languages Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-212",
        Topic: "computerscience",
        Problem: "Electrical Measurement and Instruments Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-219",
        Topic: "computerscience",
        Problem: "Analog Electronics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-121",
        Topic: "computerscience",
        Problem: "Mathematics 2 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-122",
        Topic: "computerscience",
        Problem: "Civil Engineering Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-123",
        Topic: "computerscience",
        Problem: "Machine Drawing 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-124",
        Topic: "computerscience",
        Problem: "Workshop Technology Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100P",
        Topic: "computerscience",
        Problem: "Engineering Physics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-100",
        Topic: "computerscience",
        Problem: "Engineering Mechanics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-100",
        Topic: "computerscience",
        Problem: "Electrical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "REE-100",
        Topic: "computerscience",
        Problem: "Environmental Studies and Disaster Management Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-111",
        Topic: "computerscience",
        Problem: "Mathematics 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-113",
        Topic: "computerscience",
        Problem: "Mechanical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-114",
        Topic: "computerscience",
        Problem: "Workshop Practice Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-115",
        Topic: "computerscience",
        Problem: "Engineering Drawing Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100C",
        Topic: "computerscience",
        Problem: "Engineering Chemistry Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-100",
        Topic: "computerscience",
        Problem: "Electronics and Instrumentation Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-100",
        Topic: "computerscience",
        Problem: "Inroduction to Computer Prog. and DS Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100E",
        Topic: "computerscience",
        Problem: "Commnication Skills and Personality Dev. Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
    ],
  },
  {
    topicName: "Agriculture Eng.",
    position: 1,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        S_Code: "CS-313",
        Topic: "computerscience",
        Problem: "Data Communication and Networks Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-314",
        Topic: "computerscience",
        Problem: "Computer Architecture Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-315",
        Topic: "computerscience",
        Problem: "Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-316",
        Topic: "computerscience",
        Problem: "Pulse, Digital & Wave Shaping Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-222",
        Topic: "computerscience",
        Problem: "Discrete Mathematical Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-221",
        Topic: "computerscience",
        Problem: "Computer Organization Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-222",
        Topic: "computerscience",
        Problem: "Data Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-228",
        Topic: "computerscience",
        Problem: "Communication Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-224",
        Topic: "computerscience",
        Problem: "Microprocessors 8085 & 8086 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-225",
        Topic: "computerscience",
        Problem: "System Software Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-211",
        Topic: "computerscience",
        Problem: "Mathematics 3 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-211",
        Topic: "computerscience",
        Problem: "Digital Logic Design Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-212",
        Topic: "computerscience",
        Problem: "Unix and shell programming Lab Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-213",
        Topic: "computerscience",
        Problem: "Object Oriented Programming with C++ Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-214",
        Topic: "computerscience",
        Problem: "Principles of Programming Languages Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-212",
        Topic: "computerscience",
        Problem: "Electrical Measurement and Instruments Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-219",
        Topic: "computerscience",
        Problem: "Analog Electronics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-121",
        Topic: "computerscience",
        Problem: "Mathematics 2 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-122",
        Topic: "computerscience",
        Problem: "Civil Engineering Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-123",
        Topic: "computerscience",
        Problem: "Machine Drawing 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-124",
        Topic: "computerscience",
        Problem: "Workshop Technology Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100P",
        Topic: "computerscience",
        Problem: "Engineering Physics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-100",
        Topic: "computerscience",
        Problem: "Engineering Mechanics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-100",
        Topic: "computerscience",
        Problem: "Electrical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "REE-100",
        Topic: "computerscience",
        Problem: "Environmental Studies and Disaster Management Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-111",
        Topic: "computerscience",
        Problem: "Mathematics 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-113",
        Topic: "computerscience",
        Problem: "Mechanical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-114",
        Topic: "computerscience",
        Problem: "Workshop Practice Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-115",
        Topic: "computerscience",
        Problem: "Engineering Drawing Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100C",
        Topic: "computerscience",
        Problem: "Engineering Chemistry Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-100",
        Topic: "computerscience",
        Problem: "Electronics and Instrumentation Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-100",
        Topic: "computerscience",
        Problem: "Inroduction to Computer Prog. and DS Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100E",
        Topic: "computerscience",
        Problem: "Commnication Skills and Personality Dev. Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
    ],
  },
  {
    topicName: "Mechanical Eng.",
    position: 2,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        S_Code: "CS-424",
        Topic: "computerscience",
        Problem: "Distributed Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-423",
        Topic: "computerscience",
        Problem: "Information Security Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-424",
        Topic: "computerscience",
        Problem: "Distributed Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-423",
        Topic: "computerscience",
        Problem: "Information Security Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-424",
        Topic: "computerscience",
        Problem: "Distributed Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-423",
        Topic: "computerscience",
        Problem: "Information Security Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-313",
        Topic: "computerscience",
        Problem: "Data Communication and Networks Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-314",
        Topic: "computerscience",
        Problem: "Computer Architecture Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-315",
        Topic: "computerscience",
        Problem: "Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-316",
        Topic: "computerscience",
        Problem: "Pulse, Digital & Wave Shaping Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-222",
        Topic: "computerscience",
        Problem: "Discrete Mathematical Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-221",
        Topic: "computerscience",
        Problem: "Computer Organization Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-222",
        Topic: "computerscience",
        Problem: "Data Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-228",
        Topic: "computerscience",
        Problem: "Communication Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-224",
        Topic: "computerscience",
        Problem: "Microprocessors 8085 & 8086 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-225",
        Topic: "computerscience",
        Problem: "System Software Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-211",
        Topic: "computerscience",
        Problem: "Mathematics 3 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-211",
        Topic: "computerscience",
        Problem: "Digital Logic Design Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-212",
        Topic: "computerscience",
        Problem: "Unix and shell programming Lab Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-213",
        Topic: "computerscience",
        Problem: "Object Oriented Programming with C++ Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-214",
        Topic: "computerscience",
        Problem: "Principles of Programming Languages Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-212",
        Topic: "computerscience",
        Problem: "Electrical Measurement and Instruments Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-219",
        Topic: "computerscience",
        Problem: "Analog Electronics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-121",
        Topic: "computerscience",
        Problem: "Mathematics 2 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-122",
        Topic: "computerscience",
        Problem: "Civil Engineering Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-123",
        Topic: "computerscience",
        Problem: "Machine Drawing 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-124",
        Topic: "computerscience",
        Problem: "Workshop Technology Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100P",
        Topic: "computerscience",
        Problem: "Engineering Physics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-100",
        Topic: "computerscience",
        Problem: "Engineering Mechanics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-100",
        Topic: "computerscience",
        Problem: "Electrical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "REE-100",
        Topic: "computerscience",
        Problem: "Environmental Studies and Disaster Management Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-111",
        Topic: "computerscience",
        Problem: "Mathematics 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-113",
        Topic: "computerscience",
        Problem: "Mechanical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-114",
        Topic: "computerscience",
        Problem: "Workshop Practice Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-115",
        Topic: "computerscience",
        Problem: "Engineering Drawing Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100C",
        Topic: "computerscience",
        Problem: "Engineering Chemistry Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-100",
        Topic: "computerscience",
        Problem: "Electronics and Instrumentation Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-100",
        Topic: "computerscience",
        Problem: "Inroduction to Computer Prog. and DS Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100E",
        Topic: "computerscience",
        Problem: "Commnication Skills and Personality Dev. Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
    ],
  },
  {
    topicName: "Electrical Eng.",
    position: 3,
    started: false,
    doneQuestions: 0,
    questions: [],
  },
  {
    topicName: "Electronics Eng.",
    position: 4,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        S_Code: "CS-313",
        Topic: "computerscience",
        Problem: "Data Communication and Networks Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-314",
        Topic: "computerscience",
        Problem: "Computer Architecture Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-315",
        Topic: "computerscience",
        Problem: "Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-316",
        Topic: "computerscience",
        Problem: "Pulse, Digital & Wave Shaping Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-222",
        Topic: "computerscience",
        Problem: "Discrete Mathematical Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-221",
        Topic: "computerscience",
        Problem: "Computer Organization Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-222",
        Topic: "computerscience",
        Problem: "Data Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-228",
        Topic: "computerscience",
        Problem: "Communication Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-224",
        Topic: "computerscience",
        Problem: "Microprocessors 8085 & 8086 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-225",
        Topic: "computerscience",
        Problem: "System Software Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-211",
        Topic: "computerscience",
        Problem: "Mathematics 3 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-211",
        Topic: "computerscience",
        Problem: "Digital Logic Design Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-212",
        Topic: "computerscience",
        Problem: "Unix and shell programming Lab Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-213",
        Topic: "computerscience",
        Problem: "Object Oriented Programming with C++ Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-214",
        Topic: "computerscience",
        Problem: "Principles of Programming Languages Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-212",
        Topic: "computerscience",
        Problem: "Electrical Measurement and Instruments Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-219",
        Topic: "computerscience",
        Problem: "Analog Electronics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-121",
        Topic: "computerscience",
        Problem: "Mathematics 2 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-122",
        Topic: "computerscience",
        Problem: "Civil Engineering Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-123",
        Topic: "computerscience",
        Problem: "Machine Drawing 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-124",
        Topic: "computerscience",
        Problem: "Workshop Technology Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100P",
        Topic: "computerscience",
        Problem: "Engineering Physics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-100",
        Topic: "computerscience",
        Problem: "Engineering Mechanics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-100",
        Topic: "computerscience",
        Problem: "Electrical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "REE-100",
        Topic: "computerscience",
        Problem: "Environmental Studies and Disaster Management Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-111",
        Topic: "computerscience",
        Problem: "Mathematics 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-113",
        Topic: "computerscience",
        Problem: "Mechanical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-114",
        Topic: "computerscience",
        Problem: "Workshop Practice Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-115",
        Topic: "computerscience",
        Problem: "Engineering Drawing Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100C",
        Topic: "computerscience",
        Problem: "Engineering Chemistry Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-100",
        Topic: "computerscience",
        Problem: "Electronics and Instrumentation Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-100",
        Topic: "computerscience",
        Problem: "Inroduction to Computer Prog. and DS Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100E",
        Topic: "computerscience",
        Problem: "Commnication Skills and Personality Dev. Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
    ],
  },
  {
    topicName: "Civil Eng.",
    position: 5,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        S_Code: "CS-313",
        Topic: "computerscience",
        Problem: "Data Communication and Networks Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-314",
        Topic: "computerscience",
        Problem: "Computer Architecture Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-315",
        Topic: "computerscience",
        Problem: "Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-316",
        Topic: "computerscience",
        Problem: "Pulse, Digital & Wave Shaping Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-222",
        Topic: "computerscience",
        Problem: "Discrete Mathematical Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-221",
        Topic: "computerscience",
        Problem: "Computer Organization Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-222",
        Topic: "computerscience",
        Problem: "Data Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-228",
        Topic: "computerscience",
        Problem: "Communication Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-224",
        Topic: "computerscience",
        Problem: "Microprocessors 8085 & 8086 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-225",
        Topic: "computerscience",
        Problem: "System Software Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-211",
        Topic: "computerscience",
        Problem: "Mathematics 3 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-211",
        Topic: "computerscience",
        Problem: "Digital Logic Design Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-212",
        Topic: "computerscience",
        Problem: "Unix and shell programming Lab Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-213",
        Topic: "computerscience",
        Problem: "Object Oriented Programming with C++ Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-214",
        Topic: "computerscience",
        Problem: "Principles of Programming Languages Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-212",
        Topic: "computerscience",
        Problem: "Electrical Measurement and Instruments Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-219",
        Topic: "computerscience",
        Problem: "Analog Electronics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-121",
        Topic: "computerscience",
        Problem: "Mathematics 2 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-122",
        Topic: "computerscience",
        Problem: "Civil Engineering Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-123",
        Topic: "computerscience",
        Problem: "Machine Drawing 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-124",
        Topic: "computerscience",
        Problem: "Workshop Technology Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100P",
        Topic: "computerscience",
        Problem: "Engineering Physics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-100",
        Topic: "computerscience",
        Problem: "Engineering Mechanics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-100",
        Topic: "computerscience",
        Problem: "Electrical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "REE-100",
        Topic: "computerscience",
        Problem: "Environmental Studies and Disaster Management Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-111",
        Topic: "computerscience",
        Problem: "Mathematics 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-113",
        Topic: "computerscience",
        Problem: "Mechanical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-114",
        Topic: "computerscience",
        Problem: "Workshop Practice Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-115",
        Topic: "computerscience",
        Problem: "Engineering Drawing Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100C",
        Topic: "computerscience",
        Problem: "Engineering Chemistry Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-100",
        Topic: "computerscience",
        Problem: "Electronics and Instrumentation Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-100",
        Topic: "computerscience",
        Problem: "Inroduction to Computer Prog. and DS Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100E",
        Topic: "computerscience",
        Problem: "Commnication Skills and Personality Dev. Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
    ],
  },
  {
    topicName: "Mining Eng.",
    position: 6,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        S_Code: "CS-424",
        Topic: "computerscience",
        Problem: "Distributed Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-423",
        Topic: "computerscience",
        Problem: "Information Security Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-424",
        Topic: "computerscience",
        Problem: "Distributed Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-423",
        Topic: "computerscience",
        Problem: "Information Security Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-424",
        Topic: "computerscience",
        Problem: "Distributed Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-423",
        Topic: "computerscience",
        Problem: "Information Security Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-313",
        Topic: "computerscience",
        Problem: "Data Communication and Networks Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-314",
        Topic: "computerscience",
        Problem: "Computer Architecture Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-315",
        Topic: "computerscience",
        Problem: "Database Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-316",
        Topic: "computerscience",
        Problem: "Pulse, Digital & Wave Shaping Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-222",
        Topic: "computerscience",
        Problem: "Discrete Mathematical Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-221",
        Topic: "computerscience",
        Problem: "Computer Organization Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-222",
        Topic: "computerscience",
        Problem: "Data Structure Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-228",
        Topic: "computerscience",
        Problem: "Communication Systems Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-224",
        Topic: "computerscience",
        Problem: "Microprocessors 8085 & 8086 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-225",
        Topic: "computerscience",
        Problem: "System Software Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-211",
        Topic: "computerscience",
        Problem: "Mathematics 3 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-211",
        Topic: "computerscience",
        Problem: "Digital Logic Design Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-212",
        Topic: "computerscience",
        Problem: "Unix and shell programming Lab Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-213",
        Topic: "computerscience",
        Problem: "Object Oriented Programming with C++ Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CS-214",
        Topic: "computerscience",
        Problem: "Principles of Programming Languages Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-212",
        Topic: "computerscience",
        Problem: "Electrical Measurement and Instruments Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EC-219",
        Topic: "computerscience",
        Problem: "Analog Electronics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-121",
        Topic: "computerscience",
        Problem: "Mathematics 2 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-122",
        Topic: "computerscience",
        Problem: "Civil Engineering Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-123",
        Topic: "computerscience",
        Problem: "Machine Drawing 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-124",
        Topic: "computerscience",
        Problem: "Workshop Technology Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100P",
        Topic: "computerscience",
        Problem: "Engineering Physics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-100",
        Topic: "computerscience",
        Problem: "Engineering Mechanics Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "EE-100",
        Topic: "computerscience",
        Problem: "Electrical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "REE-100",
        Topic: "computerscience",
        Problem: "Environmental Studies and Disaster Management Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-111",
        Topic: "computerscience",
        Problem: "Mathematics 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-113",
        Topic: "computerscience",
        Problem: "Mechanical Eng. 1 Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "ME-114",
        Topic: "computerscience",
        Problem: "Workshop Practice Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "CE-115",
        Topic: "computerscience",
        Problem: "Engineering Drawing Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
      {
        S_Code: "BS-100C",
        Topic: "computerscience",
        Problem: "Engineering Chemistry Sem Papers",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://drive.google.com/uc?id=1G5FckjB7vpUx1bEymLaLfgKIVF_ST3Ov",
      },
    ],
  },
];
export const version = 100000016;
